### ISSUE TITLE
Buffered reading from full blockchain gzip

### ISSUE THREAD

**Issue by TiphaineV** [ethicnology/blockchain-extractor#6]
Hi,

Thanks a lot for the package, it is really useful and well done. :) Not an issue with the package per se, but we are having trouble reading from the gzip file containing the full blockchain, since everything is dumped on a single line.

I wondered if (i) you had similar problems, and a way to read the zipped file buffered on characters rather than lines, and (ii) if it would make sense/be feasible to write one block per line in the gzip, rather than a single line.

Good day !

**Comment by ethicnology** [comment]
Hey, @TiphaineV merci :heart:  for the feedback 

Have you tried some commands listed in the [website documentation](https://ethicnology.github.io/full-bitcoin-blockchain-data-made-easy/scripts/#distillation) ?
